version: '3.8'

services:
  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: todoapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vishukk12@
      MYSQL_DATABASE: todoappdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot Application Service
  app:
    build:
      context: .
    container_name: todoapp-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todoappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vishukk12@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./target:/app

volumes:
  mysql-data:
